import NavBar from '@/components/navbar/SiteNavBar';
import '@/app/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-background flex flex-col items-center h-screen">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
