import '@/app/globals.css';
import background from '@/images/game/background.png';
import NavBar from '@/components/navbar/GameNavBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: {
  children: React.ReactNode;
  chat: React.ReactNode;
  leftWindow: React.ReactNode;
  rightWindow: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main
          className="bg-background items-center flex flex-col w-screen h-screen"
          style={{
            backgroundImage: `url(${background.src})`,
            backgroundSize: 'cover',
          }}
        >
          <NavBar />
          <div className="grid grid-cols-4 grid-rows-2 gap-2 p-2 w-full h-full">
            <div className="row-span-2">{props.leftWindow}</div>
            <div className="col-span-2">{props.children}</div>
            <div className="col-span-2 col-start-2 row-start-2">
              {props.chat}
            </div>
            <div className="row-span-2 col-start-4 row-start-1">
              {props.rightWindow}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
